<?php

return [
    'type' => 'case_tabs',
    'data' => [
        'eyebrow' => 'Klantcases',
        'title' => 'Jouw branche, onze expertise',
        'intro' => null,
        'primary_label' => 'Lees het hele verhaal',
        'secondary_label' => 'Meer over deze branche',
        'anchor' => null,
        'cases' => [
            [
                'tab' => 'Bouw & installatie',
                'client' => 'KOERS',
                'quote' => 'We kunnen investeren in iedere klant zonder ons druk te hoeven maken over ICT zaken.',
                'author' => 'Mark van der Berg',
                'role' => 'Directeur, KOERS',
                'case_url' => '/klantcases/koers',
                'industry_url' => '/it-voor-bouwbedrijven',
                'image' => 'media/cases/koers.jpg',
                'gradient_from' => null,
                'gradient_to' => null,
                'stats' => [
                    ['value' => '80+', 'label' => 'medewerkers ondersteund'],
                    ['value' => '40%', 'label' => 'minder storingen'],
                    ['value' => '99,9%', 'label' => 'uptime gegarandeerd'],
                ],
            ],
            [
                'tab' => 'Kinderdagverblijf',
                'client' => 'KindeRdam',
                'quote' => 'We kunnen investeren in ieder kind, zonder ons druk te hoeven maken over ICT zaken.',
                'author' => 'Lisette van Dijk',
                'role' => 'Directeur, KindeRdam',
                'case_url' => '/klantcases/kinderdam',
                'industry_url' => '/it-voor-kinderdagverblijven',
                'image' => null,
                'gradient_from' => '#1A6B9A',
                'gradient_to' => '#0D3D5C',
                'stats' => [
                    ['value' => '12', 'label' => 'locaties beheerd'],
                    ['value' => '150+', 'label' => 'medewerkers ondersteund'],
                    ['value' => '100%', 'label' => 'AVG compliant'],
                ],
            ],
            [
                'tab' => 'Zorg & welzijn',
                'client' => 'Zorggroep Noord',
                'quote' => 'Dankzij IT Synergy kunnen onze medewerkers zich 100% richten op de patiënt.',
                'author' => 'Sandra Meijer',
                'role' => 'IT manager, Zorggroep Noord',
                'case_url' => '/klantcases/zorggroep-noord',
                'industry_url' => '/it-voor-de-zorg',
                'image' => null,
                'gradient_from' => '#1A6B4A',
                'gradient_to' => '#0D3D28',
                'stats' => [
                    ['value' => '60+', 'label' => 'zorginstellingen'],
                    ['value' => '99,9%', 'label' => 'uptime'],
                    ['value' => 'NEN 7510', 'label' => 'gecertificeerd'],
                ],
            ],
            [
                'tab' => 'Accountancy',
                'client' => 'Van Dijk & Partners',
                'quote' => 'Vertrouwelijke klantdata staat bij ons in goede handen. IT Synergy zorgt dat dat zo blijft.',
                'author' => 'Anke van Dijk',
                'role' => 'Partner, Van Dijk & Partners',
                'case_url' => '/klantcases/van-dijk-partners',
                'industry_url' => '/it-voor-accountancy',
                'image' => null,
                'gradient_from' => '#1A4A7A',
                'gradient_to' => '#0A2040',
                'stats' => [
                    ['value' => '50+', 'label' => 'accountantskantoren'],
                    ['value' => 'ISO 27001', 'label' => 'gecertificeerd'],
                    ['value' => '100%', 'label' => 'GDPR compliant'],
                ],
            ],
        ],
    ],
];
