<?php

$sub = fn (string $emoji, string $title, string $description, string $url) => compact('emoji', 'title', 'description', 'url');

return [
    'type' => 'services_filter',
    'data' => [
        'eyebrow' => 'Onze diensten',
        'title' => 'Alles wat jouw IT nodig heeft',
        'intro' => 'Eén partner voor alle IT vraagstukken. Van werkplek tot beveiliging, van cloud tot telefonie.',
        'all_tab_label' => 'Alle oplossingen',
        'footer_button' => ['label' => 'Bekijk onze volledige producten en dienstencatalogus', 'url' => '/producten-diensten'],
        'anchor' => null,
        'cards' => [
            [
                'emoji' => '💻',
                'category' => 'Online werkplek',
                'title' => 'De slimste online werkplek',
                'text' => 'Alles wat je nodig hebt om productief te werken, veilig beheerd door IT Synergy.',
                'bullets' => ['Volledige Microsoft suite', 'Gebruikers, devices & netwerk in beheer', 'Skilled servicedesk altijd bereikbaar'],
                'link' => ['label' => 'Alles over de online werkplek', 'url' => '/online-werkplek'],
            ],
            [
                'emoji' => '🔒',
                'category' => 'IT Security',
                'title' => 'Alles krachtig beveiligd',
                'text' => 'Van endpoint tot e-mail, wij houden jouw bedrijf veilig en compliant.',
                'bullets' => ['Veilige bedrijfsprocessen', 'Ongeëvenaarde security technieken', 'Security awareness voor je team'],
                'link' => ['label' => 'Meer over IT Security', 'url' => '/it-security'],
            ],
            [
                'emoji' => '⚙️',
                'category' => 'Managed services',
                'title' => 'IT uitbesteden aan echte experts',
                'text' => 'Proactief beheer en persoonlijke support, elke dag van het jaar.',
                'bullets' => ['Beheer & support voor iedereen', 'IT omgeving klaar voor de toekomst', 'Makkelijk migreren'],
                'link' => ['label' => 'Meer over managed services', 'url' => '/managed-service-provider'],
            ],
            [
                'emoji' => '☁️',
                'category' => 'Cloud & infrastructuur',
                'title' => 'Altijd online met solide cloud infra',
                'text' => 'Schaalbaarheid en betrouwbaarheid voor moderne bedrijven.',
                'bullets' => ['Werken in de cloud', 'On-premis & hybride oplossingen', 'Volledig ingericht kantoornetwerk'],
                'link' => ['label' => 'Meer over cloud & infra', 'url' => '/it-infrastructuur'],
            ],
            [
                'emoji' => '🤖',
                'category' => 'AI oplossingen',
                'title' => 'AI die het zware werk doet',
                'text' => 'Slimme automatiseringen en Copilot integraties voor maximale tijdsbesparing.',
                'bullets' => ['Slimme A.I. automatiseringen', 'Microsoft Copilot diensten', 'Realiseer tijdsbesparing'],
                'link' => ['label' => 'Bekijk A.I. oplossingen', 'url' => '/ai-oplossingen/ai-automatiseringen'],
            ],
            [
                'emoji' => '📞',
                'category' => 'VoIP Telefonie',
                'title' => 'Zakelijk bellen via de cloud',
                'text' => 'Vast, mobiel of via Teams — altijd bereikbaar met moderne telefonie.',
                'bullets' => ['Eigen telefooncentrale in de cloud', 'Bellen via Microsoft Teams', 'Gebruik je eigen telefoon'],
                'link' => ['label' => 'Meer over VoIP Telefonie', 'url' => '/connectiviteit'],
            ],
        ],
        'categories' => [
            [
                'tab_label' => '💻 Online werkplek',
                'emoji' => '💻',
                'category' => 'Online werkplek',
                'headline' => "Simpel en snel werken\nmet de online werkplek",
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Alles over de online werkplek', 'url' => '/online-werkplek'],
                'sub_grid' => [
                    $sub('👤', 'Managed Users', 'Volledig beheer van gebruikersaccounts, rechten en identiteiten.', '/online-werkplek/managed-user'),
                    $sub('💻', 'Managed Endpoints', 'Beheer en beveiliging van alle devices in jouw organisatie.', '/online-werkplek/managed-endpoint'),
                    $sub('🟦', 'Microsoft 365', 'De complete Microsoft suite als basis van jouw werkplek.', '/online-werkplek/microsoft365'),
                    $sub('🔄', 'Evergreening', 'Jouw omgeving altijd up-to-date met de laatste versies.', '/managed-service-provider/evergreening'),
                ],
                'sub_list' => [
                    $sub('🖥️', 'Hardware', 'Laptops, desktops en werkplekken op maat geleverd en beheerd.', '/online-werkplek/managed-endpoint'),
                    $sub('✨', 'Werkplek add-ons', 'Slimme uitbreidingen die jouw werkplek nog productiever maken.', '/online-werkplek/add-ons'),
                    $sub('💬', 'Microsoft Teams', 'Vergaderen, bellen en samenwerken in één platform.', '/online-werkplek/microsoft365/microsoft-teams'),
                    $sub('☁️', 'Azure Virtual Desktop', 'Veilig werken vanuit de cloud op elk apparaat.', '/online-werkplek/azure-virtual-desktop'),
                ],
            ],
            [
                'tab_label' => '🔒 IT Security',
                'emoji' => '🔒',
                'category' => 'IT Security',
                'headline' => 'Krachtige beveiliging voor jouw gehele IT omgeving',
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Meer over IT Security', 'url' => '/it-security'],
                'sub_grid' => [
                    $sub('🛡️', 'Security technieken', 'Geavanceerde technieken om jouw omgeving te beschermen tegen moderne dreigingen.', '/it-security/cybersecurity-technieken'),
                    $sub('📋', 'Duidelijke processen', 'Heldere security processen en beleid zodat iedereen weet wat te doen.', '/it-security/cybersecurity-processen'),
                    $sub('🧑‍💼', 'Personeels awareness', 'Medewerkers zijn de eerste verdedigingslinie — wij maken ze bewust.', '/it-security/cybersecurity-voor-personeel/security-awareness'),
                    $sub('🇪🇺', 'NIS2', 'Voldoe aan de Europese NIS2-richtlijn en zorg voor aantoonbare compliance.', '/it-security/cybersecurity-processen/compliance'),
                ],
                'sub_list' => [
                    $sub('🔍', '24x7 SOC', 'Continu toezicht op jouw omgeving door ons Security Operations Center.', '/it-security/cybersecurity-processen/soc'),
                    $sub('🔑', 'Toegangsbeveiliging', 'Multi-factor authenticatie en conditional access voor veilige toegang.', '/it-security/cybersecurity-technieken/toegangsbeveiliging'),
                    $sub('🎣', 'Phishing simulaties', 'Test de weerbaarheid van medewerkers met realistische phishingaanvallen.', '/it-security/cybersecurity-voor-personeel/phishing-simulaties'),
                    $sub('🎓', 'Awareness trainingen', 'Interactieve trainingen die medewerkers cyberwijs maken.', '/it-security/cybersecurity-voor-personeel/security-awareness'),
                ],
            ],
            [
                'tab_label' => '⚙️ Managed Service Provider',
                'emoji' => '⚙️',
                'category' => 'Managed Service Provider',
                'headline' => 'IT met een glimlach, elke dag opnieuw',
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Meer over managed services', 'url' => '/managed-service-provider'],
                'sub_grid' => [
                    $sub('🎧', 'IT Support', 'Persoonlijke helpdesk support on- en offsite voor al jouw medewerkers.', '/managed-service-provider/it-support'),
                    $sub('⚙️', 'IT Beheer', 'Proactief beheer van jouw volledige IT omgeving, 24/7 gemonitord.', '/managed-service-provider/it-beheer'),
                    $sub('🧭', 'IT Strategie', 'Strategisch IT advies afgestemd op de groei van jouw organisatie.', '/managed-service-provider/it-strategie'),
                    $sub('🏗️', 'IT Consultancy & Projecten', 'Van advies tot oplevering, wij begeleiden jouw IT projecten.', '/managed-service-provider/it-consultancy'),
                ],
                'sub_list' => [
                    $sub('📊', 'PowerBI rapportages', 'Realtime inzicht in jouw IT omgeving via interactieve Power BI dashboards.', '/managed-service-provider/it-strategie/power-bi'),
                    $sub('🗺️', 'Interactieve roadmaps', 'Een visuele IT roadmap zodat je altijd weet waar je naartoe werkt.', '/managed-service-provider/it-strategie/interactieve-roadmap'),
                    $sub('🎓', 'IT Trainingen', 'Praktische trainingen zodat medewerkers het meeste uit IT halen.', '/managed-service-provider/it-trainingen'),
                    $sub('🚀', 'Onboardingtraject', 'Een soepele, gestructureerde start als nieuwe klant van IT Synergy.', '/managed-service-provider/it-consultancy/onboarding'),
                ],
            ],
            [
                'tab_label' => '☁️ Cloud & Infra',
                'emoji' => '☁️',
                'category' => 'Cloud & infrastructuur',
                'headline' => 'Altijd online met een solide cloud infrastructuur',
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Meer over werken in de cloud', 'url' => '/it-infrastructuur'],
                'sub_grid' => [
                    $sub('🏢', 'On-premises', 'Lokale servers en infrastructuur volledig beheerd door IT Synergy.', '/it-infrastructuur/on-premise'),
                    $sub('🔀', 'Hybrid cloud', 'De beste mix van lokale en cloudoplossingen voor jouw organisatie.', '/it-infrastructuur/hybride-cloud'),
                    $sub('🔵', 'Microsoft Azure', 'Schaalbare cloudoplossingen op het Microsoft Azure platform.', '/it-infrastructuur/microsoft-azure'),
                    $sub('🌐', 'Netwerk', 'Betrouwbare netwerkinfrastructuur voor kantoor en meerdere locaties.', '/online-werkplek/managed-netwerk'),
                ],
                'sub_list' => [
                    $sub('☁️', 'Cloud hosting', 'Veilige en schaalbare hosting van jouw applicaties en data in de cloud.', '/it-infrastructuur/microsoft-azure/cloud-hosting'),
                    $sub('🚚', 'Cloud migraties', 'Naadloze migratie naar de cloud zonder downtime of dataverlies.', '/it-infrastructuur/microsoft-azure/cloud-migratie'),
                ],
            ],
            [
                'tab_label' => '🤖 AI Oplossingen',
                'emoji' => '🤖',
                'category' => 'AI oplossingen',
                'headline' => 'Supercharge jouw IT met slimme AI oplossingen',
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Bekijk A.I. oplossingen', 'url' => '/ai-oplossingen/ai-automatiseringen'],
                'sub_grid' => [
                    $sub('🪄', 'Microsoft Copilot', 'AI assistent direct geïntegreerd in al jouw Microsoft 365 apps.', '/ai-oplossingen/microsoft-copilot'),
                    $sub('⚡', 'AI Automatiseringen', 'Automatiseer repetitieve taken met slimme AI-gedreven workflows.', '/ai-oplossingen/ai-automatiseringen'),
                ],
                'sub_list' => [
                    $sub('🔄', 'Power Automate', 'Slimme workflows die jouw bedrijfsprocessen versnellen en verbinden.', '/ai-oplossingen'),
                    $sub('🤖', 'Copilot Studio', 'Bouw je eigen AI-assistent op maat voor jouw organisatie.', '/ai-oplossingen'),
                    $sub('📋', 'AI Readiness Scan', 'Ontdek hoe AI-gereed jouw organisatie is en waar de kansen liggen.', '/ai-oplossingen'),
                    $sub('📄', 'Document intelligentie', 'Automatisch verwerken van facturen, contracten en andere documenten.', '/ai-oplossingen'),
                ],
            ],
            [
                'tab_label' => '📞 Connectiviteit',
                'emoji' => '📞',
                'category' => 'Connectiviteit',
                'headline' => 'Zakelijk bellen met slimme cloudtelefonie',
                'image' => 'media/ict-liefde.jpg',
                'cta' => ['label' => 'Meer over VoIP Telefonie', 'url' => '/connectiviteit'],
                'sub_grid' => [
                    $sub('📞', 'Zakelijk vast bellen', 'Een betrouwbare vaste lijn voor jouw organisatie, volledig in de cloud.', '/connectiviteit/voip-telefonie/vast-bellen'),
                    $sub('📱', 'Zakelijk mobiel bellen', 'Zakelijk bereikbaar op jouw eigen mobiele telefoon via dual-sim.', '/connectiviteit/voip-telefonie/mobiel-bellen'),
                    $sub('☁️', 'VoIP hosting', 'Een volledige telefooncentrale in de cloud zonder fysieke hardware.', '/connectiviteit/voip-telefonie/voip-hosting'),
                    $sub('💬', 'VoIP & Microsoft Teams', 'Bel zakelijk via Microsoft Teams met jouw eigen telefoonnummer.', '/connectiviteit/voip-telefonie/voip-teams'),
                ],
                'sub_list' => [
                    $sub('🔢', 'VoIP telefoonnummers', 'Neem bestaande nummers mee of kies nieuwe zakelijke nummers.', '/connectiviteit/voip-telefonie/voip-nummers'),
                    $sub('🖲️', 'VoIP toestellen', 'Professionele IP-telefoons geleverd, geconfigureerd en beheerd.', '/connectiviteit/voip-telefonie/voip-toestellen'),
                ],
            ],
        ],
    ],
];
